server:
  port: 8091
spring:
  application:
    name: "courses-enrollment"
  datasource:
    url: jdbc:h2:mem:testdb
    username: kb
    password: ''
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  config:
    import:
      - courses-enrollment-qa.yml
      - courses-enrollment-prod.yml
  profiles:
    active: qa

management:
  endpoints:
    web:
      exposure:
        include: "*"

build:
  version: 3.0.0
